---
title: "Final Project"
format: pdf
editor: visual
author: "Benji Gold and Sam Alkalay"
---

## Packages and Data

```{r libs, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels) 
library(glmnet)
library(caret) 
library(MASS)
stats <- read.csv("data/stats.csv")


stats <- replace(stats, stats =="", NA)
stats <- stats %>%
  drop_na()
view(stats)
```

## Lassos for Variable Selection
```{r lasso,warning=FALSE, message=FALSE}
# LASSO Variable Selection Basic Stats
y <- stats$All.Star
x <- model.matrix(All.Star ~ player_age + b_ab + b_total_pa + b_total_hits + 
                    b_double + b_triple + b_home_run + b_strikeout + b_walk +
                    b_k_percent + b_bb_percent + batting_avg + slg_percent +
                    on_base_percent, data = stats)
m_lasso_cv <- cv.glmnet(x, y, alpha = 1)
best_lambda <- m_lasso_cv$lambda.min
best_lambda
m_best <- glmnet(x, y, alpha = 1, lambda = best_lambda)
m_best$beta
```

```{r lasso2,warning=FALSE, message=FALSE}
# LASSO Variable Selection Advanced Stats
y <- stats$All.Star
x <- model.matrix(All.Star ~ player_age + launch_angle_avg + sweet_spot_percent + 
                    barrel + solidcontact_percent + flareburner_percent + 
                    hard_hit_percent + avg_hyper_speed + z_swing_percent + 
                    oz_swing_percent + meatball_swing_percent, data = stats)
m_lasso_cv <- cv.glmnet(x, y, alpha = 1)
best_lambda <- m_lasso_cv$lambda.min
best_lambda
m_best <- glmnet(x, y, alpha = 1, lambda = best_lambda)
m_best$beta
```

## Regressions
```{r}
#Basic model 
m1 <- glm(All.Star ~ player_age + b_ab +  b_total_hits + 
                    b_double + b_triple + b_home_run + b_strikeout +
                    b_bb_percent + batting_avg + slg_percent +
                    on_base_percent,
  data = stats,
  family = "binomial"
)
tidy(m1)
m1_aug <- augment(m1) %>% 
  mutate(prob = exp(.fitted)/(1 + exp(.fitted)),
         pred_leg = ifelse(prob > 0.5, "All-Star", "Not All-Star"))
table(m1_aug$pred_leg, m1_aug$All.Star)
```

```{r}
#Advanced model 
m2 <- glm(All.Star ~ player_age + launch_angle_avg + 
                    barrel + solidcontact_percent + flareburner_percent + 
                    hard_hit_percent + meatball_swing_percent,
  data = stats,
  family = "binomial"
)
tidy(m2)
m2_aug <- augment(m2) %>% 
  mutate(prob = exp(.fitted)/(1 + exp(.fitted)),
         pred_leg = ifelse(prob > 0.5, "All-Star", "Not All-Star"))
table(m2_aug$pred_leg, m2_aug$All.Star)

```

